language: python
dist: bionic
cache:
  pip: true
  directories:
    - /home/travis/nest-$NEST_VERSION
jobs:
  include:
      python: 3.6
      before_install:
        - wget https://neuron.yale.edu/ftp/neuron/versions/v7.7/nrn-7.7.x86_64-linux.deb
        - sudo dpkg -i nrn-7.7.x86_64-linux.deb
install:
  - source devops/check_nest_cache.sh
  - sudo apt-get install -y build-essential cmake cython libgsl-dev libltdl-dev libncurses-dev libreadline-dev openmpi-bin libopenmpi-dev
  - if [ "$HAS_NEST_CACHE" = "0" ]; then
      source devops/install_nest.sh
    else
      echo "NEST cache found, skipping installation";
    fi
  - source /home/travis/nest-$NEST_VERSION/bin/nest_vars.sh
  - source devops/install_nest_modules.sh
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
  - pip3 install coverage
script:
  - coverage run -m unittest discover -v -s ./tests
after_success:
  - bash <(curl -s https://codecov.io/bash)
